[package]
name = "matplotters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters-backend = "0.3.5"
plotters-bitmap = "0.3.3"
plotters-svg = "0.3.5"
